### ISSUE TITLE
Runtime error: wrong sensor ID or type!

### ISSUE THREAD

**Issue by Tylersuard** [adafruit/Adafruit_CircuitPython_VL53L4CD#12]
```
Traceback (most recent call last):
  File "code.py", line 10, in <module>
  File "adafruit_vl53l4cd.py", line 78, in __init__
RuntimeError: Wrong sensor ID or type!
```

I am using the correct sensor and it is plugged in and the light is on.

**Comment by caternuson** [comment]
Cross posted:
https://forums.adafruit.com/viewtopic.php?t=201790

**Comment by caternuson** [comment]
Example above works as expected testing locally:
```python
Adafruit CircuitPython 8.1.0 on 2023-05-22; Adafruit QT Py ESP32S2 with ESP32S2
>>>
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
VL53L4CD Simple Test.
--------------------
Model ID: 0xEB
Module Type: 0xAA
Timing Budget: 199
Inter-Measurement: 0
--------------------
Distance: 164.8 cm
Distance: 164.8 cm
Distance: 164.2 cm
Distance: 164.5 cm
Distance: 164.0 cm
Distance: 105.7 cm
Distance: 38.8 cm
Distance: 33.6 cm
Distance: 12.4 cm
Distance: 6.5 cm
Distance: 18.4 cm
Distance: 29.3 cm
Distance: 20.4 cm
```

Does it do the same thing if you try via REPL? Like this:
```python
Adafruit CircuitPython 8.1.0 on 2023-05-22; Adafruit QT Py ESP32S2 with ESP32S2
>>> import board
>>> import adafruit_vl53l4cd
>>> i2c = board.STEMMA_I2C() 
>>> vl53 = adafruit_vl53l4cd.VL53L4CD(i2c)
>>>
```

**Comment by Tylersuard** [comment]
That is odd that this problem would occur specifically on S3 but not on S2.  Thank you for helping.

**Comment by jposada202020** [comment]
Just for reference, Another sensor that does not work with the S3 here: https://github.com/adafruit/circuitpython/issues/7923

**Comment by caternuson** [comment]
And a couple more:
https://github.com/adafruit/circuitpython/issues/6311
https://github.com/adafruit/circuitpython/issues/8049

This looks like something S3 specific, still on going, and potentially in the underlying support software (ESP IDF)

**Comment by FoamyGuy** [comment]
I tested this sensor on a [QT S3](https://www.adafruit.com/product/5700) with VL53L4CD sensor connected via the semma cable.
```
Adafruit CircuitPython 9.2.1 on 2024-11-20; Adafruit QT Py ESP32-S3 4MB Flash 2MB PSRAM with ESP32S3
```
With the current versions of circuitpython and the driver library. It's connecting and taking readings successfully. It appears this issue has been resolved.
