### ISSUE TITLE
Nvidia Jetson Xavier NX

### ISSUE THREAD

**Issue by spcrobocar** [adafruit/Adafruit_CircuitPython_VL53L4CD#5]
Can you run this on Nvidia Jetson Xavier NX?

**Comment by caternuson** [comment]
Can try using Blinka:
https://circuitpython.org/blinka/jetson_xavier_nx/
https://learn.adafruit.com/circuitpython-libraries-on-linux-and-the-nvidia-jetson-nano/overview
